=== AlexVerzhbovski/oop-examples/GamesLabs/2015/IT-22/SF/Laba16/configSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="color" type="Color"></xs:element>
        <xs:element name="startNumber" type="Asd"></xs:element>
        <xs:element name="bgImage" type="SetImage"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Color">
    <xs:sequence>
      <xs:element name="fieldColor" type="Filter"></xs:element>
      <xs:element name="missColor" type="Filter"></xs:element>
      <xs:element name="popColor" type="Filter"></xs:element>
      <xs:element name="killColor" type="Filter"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="Filter">
    <xs:restriction base="xs:string">
      <xs:pattern value="#[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Asd">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0"></xs:minInclusive>
      <xs:maxInclusive value="2"></xs:maxInclusive>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SetImage">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0"></xs:minInclusive>
      <xs:maxInclusive value="2"></xs:maxInclusive>
    </xs:restriction>
  </xs:simpleType>
    
</xs:schema>

=== AlexVerzhbovski/oop-examples/GamesLabs/2015/IT-22/SF/Laba16/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<config 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="configSchema.xsd">
  <color>
    <fieldColor>#FF5F9EA0</fieldColor>
    <missColor>#FF0000FF</missColor>
    <popColor>#FFFFFF00</popColor>
    <killColor>#FFFF0000</killColor>
  </color>
  <startNumber>0</startNumber>
  <bgImage>2</bgImage>
</config>
